//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobit_5.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterioEmpresa
    {
        public int Id { get; set; }
        public Nullable<int> IdCriterio { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> SeCumple { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> NoConseguido { get; set; }
        public Nullable<decimal> Parcialmente { get; set; }
        public Nullable<decimal> ParteConseguido { get; set; }
        public Nullable<decimal> Totalidad { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Criterio Criterio { get; set; }
        public virtual DatosEmpresa DatosEmpresa { get; set; }
    }
}
