//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobit_5.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nivel
    {
        public Nivel()
        {
            this.Criterio = new HashSet<Criterio>();
            this.PropositoNivel = new HashSet<PropositoNivel>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProceso { get; set; }
        public string CodigoNivel { get; set; }
        public string Detalles { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual ICollection<Criterio> Criterio { get; set; }
        public virtual Proceso Proceso { get; set; }
        public virtual ICollection<PropositoNivel> PropositoNivel { get; set; }
    }
}
