//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobit_5.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        public Proceso()
        {
            this.Nivel = new HashSet<Nivel>();
            this.ProcesoEmpresa = new HashSet<ProcesoEmpresa>();
        }
    
        public int Id { get; set; }
        public string CodigoProceso { get; set; }
        public string NombreProceso { get; set; }
        public string PropositoProceso { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual ICollection<Nivel> Nivel { get; set; }
        public virtual ICollection<ProcesoEmpresa> ProcesoEmpresa { get; set; }
    }
}
